# Numpy
This is basic numerical python used for various purposes.


In [11]:
# Import the NumPy library with an alias np
import numpy as np

In [12]:
numlist = [14, 32, 93, 63, 69, 74]
numarray = np.array(numlist)
print(numarray)
print(len(numarray))

[14 32 93 63 69 74]
6


# Accessing Array Elements

In [13]:
# accessing elements is same as with usual lists in python.
print(numarray[0])
print(numarray[2])

14
93


In [14]:
# Select the values starting from index 1 up to index 3 (excluding this)
numarray[1:3]

array([32, 93])

In [15]:
# Negative index starts from the right side, 
# with the last number having index -1
numarray[-1]

# Select the values starting from index 2 up to index -1 (excluding this)
numarray[2:-1]

array([93, 63, 69])

In [16]:
# Select the values starting with index 1 
# and with index going in steps of 2
numarray[1:5:2]

array([32, 63])

In [17]:
# Select all elements with step size -1, 
# which means reversing the array
numarray[::-1]

array([74, 69, 63, 93, 32, 14])

# Simple NumPy Arithmetic

In [18]:
# Add a number to each element of the array
# Notice that this command does not update the array,
# but only gives the output after adding. same for subtraction, multiplication
#division.
print(numarray + 19)
print(numarray * 19)
print(numarray / 19)
print(numarray - 19)

[ 33  51 112  82  88  93]
[ 266  608 1767 1197 1311 1406]
[0.73684211 1.68421053 4.89473684 3.31578947 3.63157895 3.89473684]
[-5 13 74 44 50 55]


# Simple NumPy Functions

In [19]:
# Sum of the elements in the array
np.sum(numarray)

345

In [20]:
# Mean of the elements in the array
np.mean(numarray)

57.5

In [21]:
# Max of the elements in the array
np.max(numarray)

93

**Trigonometric Functions**

In [22]:
# If the values in numarray are angles of a polygon in degrees, 
# you can compute various trigonometric functions for these values.

# First convert these values into radians and then compute the functions.

numarray_radian = numarray*np.pi/180.0
numarray_radian

array([0.2443461 , 0.55850536, 1.6231562 , 1.09955743, 1.20427718,
       1.29154365])

In [23]:
# sinusoid of all the angles
np.sin(numarray_radian)

array([0.2419219 , 0.52991926, 0.99862953, 0.89100652, 0.93358043,
       0.9612617 ])

# Working with 2 1D Arrays

In [24]:
numarray1 = np.array([14, 32, 93, 63, 69, 74])
numarray2 = np.array([31, 12, 87, 56, 61,42])

In [25]:
# adding two numarrays Please not that while doing all these operations both arrays must be of same length.
numarray1+numarray2

array([ 45,  44, 180, 119, 130, 116])

In [26]:
# multipying the two arrays Returns the product of values in the array.
np.multiply(numarray1, numarray2)

array([ 434,  384, 8091, 3528, 4209, 3108])

# 2D Arrays

In [27]:
numarray1

array([14, 32, 93, 63, 69, 74])

In [28]:
# Concatenate the two 1D arrays into a bigger 1D array
# Notice the double brackets

np.concatenate((numarray1, numarray2))

array([14, 32, 93, 63, 69, 74, 31, 12, 87, 56, 61, 42])

In [29]:
# You can also concatenate them so that they become 2 rows in a 2D array
# But now we are not using the concatenate command
# Notice the double brackets

numarray2d = np.array((numarray1, numarray2))
numarray2d

array([[14, 32, 93, 63, 69, 74],
       [31, 12, 87, 56, 61, 42]])

In [30]:
# Another way to create 2D Array
# Notice the double brackets

numarray2d = np.array([[14, 32, 93, 63, 69, 74], [31, 12, 87,  9, 61, 42]])
numarray2d

array([[14, 32, 93, 63, 69, 74],
       [31, 12, 87,  9, 61, 42]])

**Accessing Elements of 2D Array**

In [31]:
numarray2d[0,3]

63

In [32]:
numarray2d[1, 4]

61

In [33]:
numarray2d[0,5]

74

**Slicing a 2D Array**

In [34]:
numarray2d

array([[14, 32, 93, 63, 69, 74],
       [31, 12, 87,  9, 61, 42]])

In [35]:
numarray2d[0:2,3:5]

array([[63, 69],
       [ 9, 61]])

**Check if its a 1D array or a 2D array using ndim property**

In [36]:
numarray1.ndim

1

In [37]:
numarray2d.ndim

2

**Check the number of rows and columns using the shape property**

In [38]:
numarray1.shape
# always keep in mind that in displayed tuple first entry is number of rows 
# and in 1d array there are only rows

(6,)

In [39]:
numarray2d.shape

(2, 6)

**Create another 1D array and append it to the 2D array as a new row**

In [40]:
# Notice the double square brackets here
numarray3 = np.array([[4, 1, 19, 22, 88, 34]])
numarray3

array([[ 4,  1, 19, 22, 88, 34]])

In [41]:
# axis 0 is row.
np.concatenate((numarray2d, numarray3), axis=0)

array([[14, 32, 93, 63, 69, 74],
       [31, 12, 87,  9, 61, 42],
       [ 4,  1, 19, 22, 88, 34]])

In [42]:
# Notice that the above function did not update numarray2d, 
# but just gave the output as a new NumPy array without saving it anywhere.

numarray2d

array([[14, 32, 93, 63, 69, 74],
       [31, 12, 87,  9, 61, 42]])

**1D array with 6 elements vs. 2D array with 1 row and 6 columns**

In [43]:
# 1D array with 6 elements
# One square bracket used

print(np.array([4, 1, 19, 22, 88, 34]).ndim)
print(np.array([4, 1, 19, 22, 88, 34]).shape)

1
(6,)


In [44]:
# 2D array with 1 row and 6 columns
# Two square brackets used

print(np.array([[4, 1, 19, 22, 88, 34]]).ndim)
print(np.array([[4, 1, 19, 22, 88, 34]]).shape)

2
(1, 6)


**Create another 1D array and append it to the 2D array as a new column**

In [45]:
# Notice the double square brackets here

numarray4 = np.array([[4, 1]])

In [46]:
# axis 1 is column
np.concatenate((numarray2d, numarray4.T), axis=1)

array([[14, 32, 93, 63, 69, 74,  4],
       [31, 12, 87,  9, 61, 42,  1]])

In [47]:
numarray4.shape

(1, 2)

In [48]:
# Taking the transpose of the matrix.
numarray4.T.shape

(2, 1)

# Reshaping an array

Another way to change the shape and dimensions of an array is to reshape it

In [49]:
numarray1

array([14, 32, 93, 63, 69, 74])

In [50]:
# Make numarray1 into a 2D array with 2 rows and 3 columns
# note that product column and rows must be a size of array.
numarray1.reshape(2,3)

array([[14, 32, 93],
       [63, 69, 74]])

In [51]:
numarray3

array([[ 4,  1, 19, 22, 88, 34]])

In [52]:
# Make numarray1 into a 2D array with 3 rows and 2 columns
numarray3.reshape(3,2)

array([[ 4,  1],
       [19, 22],
       [88, 34]])

In [53]:
# -1 means it automatically adjust the value for column.
numarray3.reshape(3,-1)

array([[ 4,  1],
       [19, 22],
       [88, 34]])

In [54]:
numarray3.reshape(1,6)

array([[ 4,  1, 19, 22, 88, 34]])

In [55]:
# This creates a 2D array with 6 rows and 1 column
numarray3.reshape(6,1)

array([[ 4],
       [ 1],
       [19],
       [22],
       [88],
       [34]])

In [56]:
numarray3.T

array([[ 4],
       [ 1],
       [19],
       [22],
       [88],
       [34]])

**Reshaping a 2D array**

In [57]:
numarray2d

array([[14, 32, 93, 63, 69, 74],
       [31, 12, 87,  9, 61, 42]])

In [58]:
numarray2d.reshape(3,-1)

array([[14, 32, 93, 63],
       [69, 74, 31, 12],
       [87,  9, 61, 42]])

# NumPy Functions on 2D Arrays

In [59]:
# Maximum value in the array
np.max(numarray2d)

93

In [60]:
# Maximum value of each column
np.max(numarray2d,axis=0)

array([31, 32, 93, 63, 69, 74])

In [61]:
# Maximum value of each row
np.max(numarray2d,axis=1)

array([93, 87])

# Searching Arrays

In [62]:
numarray1 = np.array([14, 32, 93, 63, 69, 74])

In [63]:
np.where(numarray1==93)

(array([2], dtype=int64),)

In [64]:
numarray1 = np.array([14, 32, 93, 63, 93, 74])

In [65]:
np.where(numarray1==93)

(array([2, 4], dtype=int64),)

In [66]:
numarray2d = np.array((numarray1, numarray2))

In [67]:
numarray2d

array([[14, 32, 93, 63, 93, 74],
       [31, 12, 87, 56, 61, 42]])

In [68]:
l = np.where(numarray2d == 93)
l

(array([0, 0], dtype=int64), array([2, 4], dtype=int64))

# Sorting an Array

In [69]:
numarray1

array([14, 32, 93, 63, 93, 74])

In [70]:
np.sort(numarray1)

array([14, 32, 63, 74, 93, 93])

In [71]:
# Sort an array in descending order
np.flip(numarray1)

array([74, 93, 63, 93, 32, 14])

In [72]:
numarray2d

array([[14, 32, 93, 63, 93, 74],
       [31, 12, 87, 56, 61, 42]])

In [73]:
np.sort(numarray2d,axis=0)

array([[14, 12, 87, 56, 61, 42],
       [31, 32, 93, 63, 93, 74]])

In [74]:
np.sort(numarray2d,axis=1)

array([[14, 32, 63, 74, 93, 93],
       [12, 31, 42, 56, 61, 87]])

# Filter Arrays

In [75]:
numarray1

array([14, 32, 93, 63, 93, 74])

In [76]:
numarray1[numarray1 > 50]

array([93, 63, 93, 74])

In [77]:
numarray2d

array([[14, 32, 93, 63, 93, 74],
       [31, 12, 87, 56, 61, 42]])

In [78]:
numarray2d[numarray2d > 50]

array([93, 63, 93, 74, 87, 56, 61])

# Create Special Arrays

**Generate an array with a certain number of equally spaced values**


In [79]:
# np.linspace(start, stop, num)
# start : starting value
# stop : last value
# num : number of values to generate

np.linspace(0, 2, 10)

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

**Generate an array of equally spaced values with a certain step size**

In [80]:
# np.arange(start, stop, step)
# start : starting value
# stop : last value
# step : step size to use

np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [81]:
np.arange(4,20,3)

array([ 4,  7, 10, 13, 16, 19])

**Generate an array of all zeros**

In [82]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [83]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

**Generate an array of all ones**

In [84]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [85]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

# Broadcasting

Broadcasting refers to how NumPy does arithmetic operations with arrays of different dimensions

In [86]:
numarray2d

array([[14, 32, 93, 63, 93, 74],
       [31, 12, 87, 56, 61, 42]])

In [87]:
numarray5 = np.array([[1,2, 3, 4, 5, 6]])
numarray5

array([[1, 2, 3, 4, 5, 6]])

In [88]:
numarray2d+numarray5

array([[15, 34, 96, 67, 98, 80],
       [32, 14, 90, 60, 66, 48]])

In [89]:
numarray2d + numarray2d

array([[ 28,  64, 186, 126, 186, 148],
       [ 62,  24, 174, 112, 122,  84]])

In [90]:
numarray2d

array([[14, 32, 93, 63, 93, 74],
       [31, 12, 87, 56, 61, 42]])

In [91]:
numarray5 = np.array([[1,2]])
numarray5

array([[1, 2]])

In [92]:
numarray2d+numarray5.T

array([[15, 33, 94, 64, 94, 75],
       [33, 14, 89, 58, 63, 44]])

# Matrix Multiplication

In [93]:
numarray1

array([14, 32, 93, 63, 93, 74])

In [94]:
numarray2

array([31, 12, 87, 56, 61, 42])

In [95]:
# Element by Element Multiplication
numarray1*numarray2

array([ 434,  384, 8091, 3528, 5673, 3108])

In [96]:
# Element by Element Multiplication
np.multiply(numarray1,numarray2)

array([ 434,  384, 8091, 3528, 5673, 3108])

**Dot Product of two 1D arrays (vectors)**

In [97]:
np.dot(numarray1, numarray2)

21218

In [98]:
numarray1@numarray2

21218

In [99]:
np.matmul(numarray1, numarray2)

21218

In [100]:
numarray2d

array([[14, 32, 93, 63, 93, 74],
       [31, 12, 87, 56, 61, 42]])

In [116]:
numarray6 = np.array([2,3])
numarray6

array([2, 3])

In [102]:
numarray2d.T

array([[14, 31],
       [32, 12],
       [93, 87],
       [63, 56],
       [93, 61],
       [74, 42]])

**Matrix Multiplication of a 2D array with a 1D array**

In [103]:
np.matmul(numarray2d.T, numarray6)

array([121, 100, 447, 294, 369, 274])

In [104]:
np.dot(numarray2d.T, numarray6)

array([121, 100, 447, 294, 369, 274])

In [105]:
numarray2d.T@numarray6

array([121, 100, 447, 294, 369, 274])

In [106]:
numarray2d.T*numarray6

array([[ 28,  93],
       [ 64,  36],
       [186, 261],
       [126, 168],
       [186, 183],
       [148, 126]])

**Matrix Multiplication of two 2D Arrays**

In [107]:
numarray2d_1 = np.array([[14, 32, 45], [31, 12, 56]])
numarray2d_2 = np.array([[63, 9], [93, 74]])

In [108]:
numarray2d_1

array([[14, 32, 45],
       [31, 12, 56]])

In [109]:
numarray2d_2

array([[63,  9],
       [93, 74]])

In [110]:
numarray2d_1.T@numarray2d_2

array([[3765, 2420],
       [3132, 1176],
       [8043, 4549]])

In [111]:
14*63+31*93

3765

**Comparison between np.dot, np.matmul and @**

In [112]:
numarray1

array([14, 32, 93, 63, 93, 74])

In [113]:
np.dot(numarray1,2)

array([ 28,  64, 186, 126, 186, 148])

In [117]:
np.matmul(numarray1,2)

ValueError: matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

# Flatten an Array

In [118]:
numarray2d

array([[14, 32, 93, 63, 93, 74],
       [31, 12, 87, 56, 61, 42]])

In [120]:
np.ndarray.flatten(numarray2d)

array([14, 32, 93, 63, 93, 74, 31, 12, 87, 56, 61, 42])

In [121]:
numarray2d.reshape(1,-1)

array([[14, 32, 93, 63, 93, 74, 31, 12, 87, 56, 61, 42]])

# Create an Array with Random Elements

In [122]:
# Generate a 1D array with 6 elements whose values are 
# randomly chosen from the interval (0,1)
np.random.rand(6)

array([0.07647021, 0.45115948, 0.46555347, 0.47809795, 0.58792021,
       0.23273371])

In [123]:
# Generate a 2D array with shape (2,4) whose values are 
# randomly chosen from the interval (0,1)
np.random.rand(2,4)

array([[0.27724383, 0.88337563, 0.61657549, 0.74730989],
       [0.47690144, 0.20190945, 0.19520041, 0.96513065]])

In [124]:
# Generate a 1D array with 7 elements whose values are 
# random integers between 3 and 10
np.random.randint(3, 10, 7)

array([5, 4, 5, 7, 8, 3, 8])

In [125]:
# Generate a 2D array of shape (2, 4) whose values are 
# random integers between 3 and 10
np.random.randint(3, 10, (2, 4))

array([[9, 9, 5, 5],
       [9, 4, 9, 7]])